[package]
name = "wifitools"
version = "0.1.0"
edition = "2021"

[dependencies]
rusty_network_manager = "0.5.2"
tokio = { version = "1.40.0", features = ["full"] }
tokio-stream = "0.1.15"
zbus = "4.4.0"
zvariant = "4.2.0"
