[package]
name = "mmcli-test"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.22"
logging = { version = "0.1.0", path = "../../../logging" }
mmcli = { version = "0.1.0", path = "../.." }
tokio = { version = "1.40.0", features = ["full"] }
