[package]
name = "canparse"
version = "0.1.0"
edition = "2021"

[dependencies]
cantool = { version = "0.1.0", path = "../.." }
logging = { version = "0.1.0", path = "../../../logging" }
tokio = { version = "1.40.0", features = ["full"] }
